# Generated by Django 3.2.9 on 2022-04-07 17:21

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20220406_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='qfourchoicesquestion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qtrueorfalsequestion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 7, 17, 21, 34, 405500, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qfourchoicesquestion',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qtrueorfalsequestion',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
