# Generated by Django 3.2.9 on 2022-04-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20220416_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1),
        ),
    ]
