# Generated by Django 3.2.9 on 2022-04-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20220415_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='age_from',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Minimum Age Of Quiz Takers'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='age_to',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Maximum Age Of Quiz Takers'),
        ),
    ]
