# Generated by Django 3.2.9 on 2022-04-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20220416_1808'),
        ('category', '0001_initial'),
        ('core', '0041_alter_profile_categories'),
        ('quiz', '0055_auto_20220416_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourchoicesquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trueorfalsequestion',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', related_query_name='categories', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fourChoicesQuestions',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestions', related_query_name='fourChoicesQuestions', to='question.FourChoicesQuestion'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='trueOrFalseQuestions',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestions', related_query_name='trueOrFalseQuestions', to='question.TrueOrFalseQuestion'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FourChoicesQuestion',
        ),
        migrations.DeleteModel(
            name='TrueOrFalseQuestion',
        ),
    ]
