# Generated by Django 3.2.9 on 2022-04-17 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 1, 7, 34, 707322, tzinfo=utc)),
        ),
    ]
