# Generated by Django 3.2.9 on 2022-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options'),
        ('diary', '0006_auto_20220130_2026'),
        ('core', '0003_auto_20220202_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='diaries',
            field=models.ManyToManyField(to='diary.Diary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(to='todo.Task'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
