# Generated by Django 3.2.9 on 2022-04-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streak',
            options={},
        ),
    ]
