# Generated by Django 3.2.9 on 2022-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_streak_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='dislike',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="What don't you like about this app?"),
        ),
        migrations.AddField(
            model_name='interest',
            name='modifier',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='What do you want us to add to this app?'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='What do you like most about this app?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationlity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State Of Origin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='state Of Residence'),
        ),
    ]
