# Generated by Django 3.2.9 on 2022-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220207_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diaries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quizAttempted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quizCreated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tasks',
        ),
    ]
