# Generated by Django 3.2.9 on 2022-03-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220225_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
