# Generated by Django 3.2.9 on 2022-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20220319_1051'),
        ('quiz', '0035_quiztaker'),
        ('core', '0028_alter_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profileCategories', to='quiz.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourChoicesQuestionsMissed',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestionsMissed', to='question.QFourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questionAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='questionAvgScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizAvgScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizTaken',
            field=models.ManyToManyField(blank=True, related_name='profileQuizTaken', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trueOrFalseQuestionsMissed',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestionsMissed', to='question.QTrueOrFalseQuestion'),
        ),
    ]
