# Generated by Django 3.2.9 on 2022-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20220403_0300'),
        ('core', '0035_auto_20220402_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='fourChoicesQuestionsTaken',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestionsTaken', to='question.QFourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trueOrFalseQuestionsTaken',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestionsTaken', to='question.QTrueOrFalseQuestion'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
