# Generated by Django 3.2.9 on 2021-12-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
    ]
