# Generated by Django 3.2.9 on 2022-01-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quizzes_average_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
