# Generated by Django 3.2.9 on 2022-02-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quizzes_average_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
