# Generated by Django 3.2.9 on 2022-02-18 02:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20220213_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='category',
            field=models.ManyToManyField(to='quiz.Category'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='number_of_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='number_times_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
