# Generated by Django 3.2.9 on 2022-02-24 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_rename_quizzes_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempter',
            old_name='completed',
            new_name='dateCompleted',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='date_registered',
            new_name='dateRegistered',
        ),
        migrations.AddField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 22, 6, 45, 982987, tzinfo=utc)),
        ),
    ]
