# Generated by Django 3.2.9 on 2022-02-25 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20220224_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 25, 0, 16, 5, 129491, tzinfo=utc)),
        ),
    ]
