# Generated by Django 3.2.9 on 2022-03-01 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20220302_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 23, 48, 18, 94718, tzinfo=utc)),
        ),
    ]
