# Generated by Django 3.2.9 on 2022-03-02 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0023_alter_attempt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourChoicesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('form', models.CharField(default='fourChoicesQuestion', max_length=30)),
                ('question_text', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/quiz/')),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('answer4', models.CharField(max_length=200)),
                ('correct', models.CharField(choices=[('answer1', 'answer1'), ('answer2', 'answer2'), ('answer3', 'answer3'), ('answer4', 'answer4')], max_length=100)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('solutionThumbnail', models.ImageField(blank=True, null=True, upload_to='images/quiz/')),
                ('points', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('form', models.CharField(default='trueOrFalseQuestion', max_length=20)),
                ('question_text', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/quiz/')),
                ('answer1', models.CharField(default='True', max_length=20)),
                ('answer2', models.CharField(default='False', max_length=20)),
                ('correct', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=100)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('solutionThumbnail', models.ImageField(blank=True, null=True, upload_to='images/quiz/')),
                ('points', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='dateRegistered',
            new_name='date_registered',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='number_times_taken',
            new_name='number_of_questions',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_average_score',
            new_name='gross_average_score',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='attempter',
            name='dateCompleted',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='attempt',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='question_number_of_times_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='quiz_number_of_times_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(related_name='categories', related_query_name='categories', to='quiz.Category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60)], null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lastQuestionIndex',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questionLength',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffleable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='totalScore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempter',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.AddField(
            model_name='quiz',
            name='fourChoicesQuestions',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestions', related_query_name='fourChoicesQuestions', to='quiz.FourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='trueOrFalseQuestions',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestions', related_query_name='trueOrFalseQuestions', to='quiz.TrueOrFalseQuestion'),
        ),
    ]
