# Generated by Django 3.2.9 on 2022-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20220303_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1),
        ),
    ]
