# Generated by Django 3.2.9 on 2022-03-08 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0031_auto_20220306_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
