# Generated by Django 3.2.9 on 2022-03-08 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0032_quiz_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='liked',
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
