# Generated by Django 3.2.9 on 2022-03-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_auto_20220320_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='thumbnail',
        ),
    ]
