# Generated by Django 3.2.9 on 2022-03-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20220326_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='duration',
            new_name='duration_in_minutes',
        ),
    ]
