# Generated by Django 3.2.9 on 2022-03-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_alter_trueorfalsequestion_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
