# Generated by Django 3.2.9 on 2022-04-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_alter_quiz_solution_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='answer1NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='answer2NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='answer3NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='answer4NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='answer1NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='answer2NumberOfTimesTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
