# Generated by Django 3.2.9 on 2022-04-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20220406_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='shuffleable',
            new_name='shuffleQuestions',
        ),
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='shuffleAnswers',
            field=models.BooleanField(default=False),
        ),
    ]
