# Generated by Django 3.2.9 on 2022-04-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_auto_20220408_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=200)),
                ('ban', models.BooleanField(default=False)),
                ('reportCount', models.PositiveSmallIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('quiz', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz')),
            ],
        ),
    ]
