# Generated by Django 3.2.9 on 2022-04-11 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0049_quizlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlink',
            name='reporters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='quiz',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quizlink', to='quiz.quiz'),
        ),
    ]
