# Generated by Django 3.2.9 on 2022-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20220414_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='age_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='age_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
