# Generated by Django 3.2.9 on 2022-01-18 01:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
