# Generated by Django 3.2.9 on 2022-01-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
