# Generated by Django 3.2.9 on 2022-01-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='photo',
        ),
    ]
