# Generated by Django 3.2.9 on 2022-01-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_diary_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='isAnAd',
        ),
    ]
