# Generated by Django 3.2.9 on 2022-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20220130_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
