# Generated by Django 3.2.9 on 2022-02-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_diary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='post',
            field=models.TextField(max_length=1000),
        ),
    ]
