# Generated by Django 3.2.9 on 2022-03-06 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0031_auto_20220306_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('lastQuestionIndex', models.PositiveSmallIntegerField(default=0)),
                ('questionLength', models.PositiveSmallIntegerField(default=0)),
                ('totalScore', models.PositiveSmallIntegerField(default=0)),
                ('shuffleable', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('gross_average_score', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('public', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('duration', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60)], null=True)),
                ('draft', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='draft_categories', related_query_name='draft_categories', to='quiz.Category')),
                ('fourChoicesQuestions', models.ManyToManyField(blank=True, related_name='draft_fourChoicesQuestions', related_query_name='draft_fourChoicesQuestions', to='quiz.FourChoicesQuestion')),
                ('trueOrFalseQuestions', models.ManyToManyField(blank=True, related_name='draft_trueOrFalseQuestions', related_query_name='draft_trueOrFalseQuestions', to='quiz.TrueOrFalseQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DraftQuizzes',
                'ordering': ['-date', 'attempts'],
            },
        ),
    ]
