# Generated by Django 3.2.9 on 2022-03-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftquiz',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DraftTrueOrFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('form', models.CharField(default='trueOrFalseQuestion', max_length=20)),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answer1', models.CharField(default='True', max_length=20)),
                ('answer2', models.CharField(default='False', max_length=20)),
                ('correct', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=100, null=True)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('solutionThumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('points', models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1)),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftFourChoicesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1)),
                ('form', models.CharField(default='fourChoicesQuestion', max_length=30)),
                ('question_text', models.TextField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('answer1', models.CharField(blank=True, max_length=200, null=True)),
                ('answer2', models.CharField(blank=True, max_length=200, null=True)),
                ('answer3', models.CharField(blank=True, max_length=200, null=True)),
                ('answer4', models.CharField(blank=True, max_length=200, null=True)),
                ('correct', models.CharField(blank=True, choices=[('answer1', 'answer1'), ('answer2', 'answer2'), ('answer3', 'answer3'), ('answer4', 'answer4')], max_length=100, null=True)),
                ('solution', models.TextField(blank=True, max_length=500, null=True)),
                ('solutionThumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('points', models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1)),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('relevance', models.IntegerField(default=0)),
                ('number_of_quizzes', models.PositiveIntegerField(default=0)),
                ('number_of_questions', models.PositiveIntegerField(default=0)),
                ('quiz_number_of_times_taken', models.PositiveIntegerField(default=0)),
                ('question_number_of_times_taken', models.PositiveIntegerField(default=0)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DraftCategories',
            },
        ),
    ]
