# Generated by Django 3.2.9 on 2022-03-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20220306_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftfourchoicesquestion',
            name='form',
        ),
        migrations.RemoveField(
            model_name='draftfourchoicesquestion',
            name='index',
        ),
        migrations.RemoveField(
            model_name='drafttrueorfalsequestion',
            name='form',
        ),
        migrations.RemoveField(
            model_name='drafttrueorfalsequestion',
            name='index',
        ),
        migrations.DeleteModel(
            name='DraftCategory',
        ),
    ]
