# Generated by Django 3.2.9 on 2022-04-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('lastQuestionIndex', models.PositiveSmallIntegerField(default=0)),
                ('questionLength', models.PositiveSmallIntegerField(default=0)),
                ('totalScore', models.PositiveSmallIntegerField(default=0)),
                ('shuffleQuestions', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('gross_average_score', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('public', models.BooleanField(default=True)),
                ('duration_in_minutes', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60)], default=3)),
                ('solution_quality', models.IntegerField(default=0)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('age_from', models.PositiveSmallIntegerField(null=True, verbose_name='Minimum Age Of Quiz Takers')),
                ('age_to', models.PositiveSmallIntegerField(null=True, verbose_name='Maximum Age Of Quiz Takers')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', related_query_name='categories', to='category.Category')),
                ('fourChoicesQuestions', models.ManyToManyField(blank=True, related_name='fourChoicesQuestions', related_query_name='fourChoicesQuestions', to='question.FourChoicesQuestion')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('solution_validators', models.ManyToManyField(blank=True, related_name='quiz_solution_validators', to=settings.AUTH_USER_MODEL)),
                ('trueOrFalseQuestions', models.ManyToManyField(blank=True, related_name='trueOrFalseQuestions', related_query_name='trueOrFalseQuestions', to='question.TrueOrFalseQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuizLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=200)),
                ('ban', models.BooleanField(default=False)),
                ('reportCount', models.PositiveSmallIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('quiz', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quizlink', to='quiz.quiz')),
                ('reporters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-percentage', '-score'],
            },
        ),
    ]
