# Generated by Django 3.2.9 on 2022-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempter',
            options={'ordering': ['-percentage', '-score', 'timeTaken']},
        ),
        migrations.AddField(
            model_name='attempter',
            name='timeTaken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='link',
            field=models.URLField(verbose_name='Link/URL'),
        ),
        migrations.AlterField(
            model_name='quizlink',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
