# Generated by Django 3.2.9 on 2022-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='gross_average_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
