# Generated by Django 3.2.9 on 2022-01-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20220112_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='average_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='total_average_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
