# Generated by Django 3.2.9 on 2022-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220112_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='average_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
