# Generated by Django 3.2.9 on 2022-01-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizzes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['-date', 'attempts'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
