# Generated by Django 3.2.9 on 2022-01-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quizzes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
