# Generated by Django 3.2.9 on 2022-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shuffleable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
