# Generated by Django 3.2.9 on 2022-02-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20220218_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_text',
            field=models.TextField(max_length=1000),
        ),
    ]
