# Generated by Django 3.2.9 on 2022-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20220303_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/quiz/'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/quiz/'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[], default=1),
        ),
    ]
