# Generated by Django 3.2.9 on 2022-03-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_quiztaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempter',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='attempter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fourchoicesquestion',
            name='solutionThumbnail',
        ),
        migrations.RemoveField(
            model_name='fourchoicesquestion',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='trueorfalsequestion',
            name='solutionThumbnail',
        ),
        migrations.RemoveField(
            model_name='trueorfalsequestion',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Attempter',
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
    ]
