# Generated by Django 3.2.9 on 2022-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_remove_category_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date', '-attempts'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='solution_quality',
            field=models.IntegerField(default=0),
        ),
    ]
