# Generated by Django 3.2.9 on 2022-04-01 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0043_auto_20220401_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='solution_validators',
            field=models.ManyToManyField(related_name='quiz_solution_validators', to=settings.AUTH_USER_MODEL),
        ),
    ]
