# Generated by Django 3.2.9 on 2022-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='answer1',
            field=models.CharField(max_length=200, verbose_name='First Option'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='answer2',
            field=models.CharField(max_length=200, verbose_name='Second Option'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='answer3',
            field=models.CharField(max_length=200, verbose_name='Third Option'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='answer4',
            field=models.CharField(max_length=200, verbose_name='Fourth Option'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='correct',
            field=models.CharField(choices=[('answer1', 'answer1'), ('answer2', 'answer2'), ('answer3', 'answer3'), ('answer4', 'answer4')], max_length=100, verbose_name='Correct Option'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='duration_in_seconds',
            field=models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=30, verbose_name='Duration In Seconds'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='shuffleAnswers',
            field=models.BooleanField(default=False, verbose_name='Shuffle The Answers'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='solution',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='oolution'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='correct',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=100, verbose_name='Correct Option'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='duration_in_seconds',
            field=models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=20, verbose_name='Duration In Seconds'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='solution',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Solution'),
        ),
    ]
