# Generated by Django 3.2.9 on 2022-03-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qfourchoicesquestion',
            name='points',
        ),
        migrations.RemoveField(
            model_name='qtrueorfalsequestion',
            name='points',
        ),
    ]
