# Generated by Django 3.2.9 on 2022-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220418_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='solution',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Solution'),
        ),
    ]
