# Generated by Django 3.2.9 on 2022-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20220418_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fourchoicesquestion',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='trueorfalsequestion',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
