# Generated by Django 3.2.9 on 2022-03-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20220319_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qfourchoicesquestion',
            old_name='duration',
            new_name='duration_in_seconds',
        ),
        migrations.RenameField(
            model_name='qtrueorfalsequestion',
            old_name='duration',
            new_name='duration_in_seconds',
        ),
    ]
