# Generated by Django 3.2.9 on 2022-04-03 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0008_auto_20220401_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qfourchoicesquestion',
            name='solution_validators',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestion_solution_validators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qtrueorfalsequestion',
            name='solution_validators',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalse_solution_validators', to=settings.AUTH_USER_MODEL),
        ),
    ]
