# Generated by Django 3.2.9 on 2022-04-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinEarnerLeaderBoard',
            new_name='CoinsEarnerLeaderBoard',
        ),
        migrations.RenameField(
            model_name='coinsearnerleaderboard',
            old_name='leaders',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='streakleaderboard',
            old_name='leaders',
            new_name='leader',
        ),
        migrations.CreateModel(
            name='ReferralLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refers', models.PositiveIntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
