# Generated by Django 3.2.9 on 2022-02-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
