# Generated by Django 3.2.9 on 2022-02-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20220205_1828'),
        ('diary', '0007_diary_photo'),
        ('todo', '0003_task_updated'),
        ('core', '0008_auto_20220206_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diaries',
            field=models.ManyToManyField(blank=True, null=True, to='diary.Diary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizAttempted',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_attempted', to='quiz.Quizzes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizCreated',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_created', to='quiz.Quizzes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='todo.Task'),
        ),
    ]
