# Generated by Django 3.2.9 on 2022-02-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220224_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='user',
        ),
        migrations.AddField(
            model_name='streak',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
