# Generated by Django 3.2.9 on 2022-03-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_streak_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='date',
        ),
        migrations.AddField(
            model_name='streak',
            name='usedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
