# Generated by Django 3.2.9 on 2022-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220302_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
