# Generated by Django 3.2.9 on 2022-03-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220304_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='streak',
            options={'ordering': ['-length', '-question']},
        ),
    ]
