# Generated by Django 3.2.9 on 2022-03-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_follower_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-coins',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='refercount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
