# Generated by Django 3.2.9 on 2022-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.FloatField(default=1000.0),
        ),
    ]
