# Generated by Django 3.2.9 on 2022-03-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220320_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
    ]
