# Generated by Django 3.2.9 on 2022-04-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220329_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='usedDate',
            new_name='currentDate',
        ),
    ]
