# Generated by Django 3.2.9 on 2022-04-12 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220404_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 6, 59, 19, 584056, tzinfo=utc)),
        ),
    ]
