# Generated by Django 3.2.9 on 2022-04-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_link_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
