# Generated by Django 3.2.9 on 2022-02-25 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizListPage', models.PositiveIntegerField(default=0)),
                ('quizDetailPage', models.PositiveIntegerField(default=0)),
                ('quizcreationPage', models.PositiveIntegerField(default=0)),
                ('quizTakenPage', models.PositiveIntegerField(default=0)),
                ('quizSubmitPage', models.PositiveIntegerField(default=0)),
                ('quizUpdatePage', models.PositiveIntegerField(default=0)),
                ('quizDeletePage', models.PositiveIntegerField(default=0)),
                ('questionCreationPage', models.PositiveIntegerField(default=0)),
                ('questionUpdatePage', models.PositiveIntegerField(default=0)),
                ('qustionDeletePage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionCreationPage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionUpdatePage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionDeletePage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionCreationPage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionUpdatePage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionDeletePage', models.PositiveIntegerField(default=0)),
                ('pdfDownload', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'PageCounter',
            },
        ),
        migrations.CreateModel(
            name='UserPageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizListPage', models.PositiveIntegerField(default=0)),
                ('quizDetailPage', models.PositiveIntegerField(default=0)),
                ('quizcreationPage', models.PositiveIntegerField(default=0)),
                ('quizTakenPage', models.PositiveIntegerField(default=0)),
                ('quizSubmitPage', models.PositiveIntegerField(default=0)),
                ('quizUpdatePage', models.PositiveIntegerField(default=0)),
                ('quizDeletePage', models.PositiveIntegerField(default=0)),
                ('questionCreationPage', models.PositiveIntegerField(default=0)),
                ('questionUpdatePage', models.PositiveIntegerField(default=0)),
                ('qustionDeletePage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionCreationPage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionUpdatePage', models.PositiveIntegerField(default=0)),
                ('fourChoicesQuestionDeletePage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionCreationPage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionUpdatePage', models.PositiveIntegerField(default=0)),
                ('trueOrFalseQuestionDeletePage', models.PositiveIntegerField(default=0)),
                ('pdfDownload', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserPageCounter',
            },
        ),
    ]
