# Generated by Django 3.2.9 on 2022-03-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecounter',
            old_name='quizcreationPage',
            new_name='quizCreationPage',
        ),
        migrations.RenameField(
            model_name='userpagecounter',
            old_name='quizcreationPage',
            new_name='quizCreationPage',
        ),
    ]
