# Generated by Django 3.2.9 on 2022-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postad',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
