# Generated by Django 3.2.9 on 2022-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20220318_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='qfourchoicesquestion',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qfourchoicesquestion',
            name='avgScore',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='qtrueorfalsequestion',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qtrueorfalsequestion',
            name='avgScore',
            field=models.FloatField(default=0.0),
        ),
    ]
