# Generated by Django 3.2.9 on 2022-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20220326_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qfourchoicesquestion',
            name='solution',
            field=models.TextField(default='The creator of this quiz did not provide any solution for this question!', max_length=500),
        ),
        migrations.AlterField(
            model_name='qtrueorfalsequestion',
            name='solution',
            field=models.TextField(default='The creator of this quiz did not provide any solution for this question!', max_length=500),
        ),
    ]
